### ISSUE TITLE
[question] is it possible to implement end-to-end encryption with anycable?

### ISSUE THREAD

**Issue by 0xMostafa** [anycable/anycable-go#209]
I'm evaluating anycable for a new project that requires end to end encryption of chats.

Is it possible to implement end to end encryption with anycable?

**Comment by palkan** [comment]
Yes, that should be possible. We don't have anything built-in for that (yet), but all you need from AnyCable is a transport, the actual logic (keys exchange, encrypting/decrypting messages) can be implemented independently.

The way I thought about this is as follows:

- A dedicated channel (channel class + unique identifiers) is created for participating peers and is used to exchange public keys. Probably, special message types must be added to manage keys. So, it could be a protocol extension.

- Clients responsible for storing keys; there, probably, must be some key recovery mechanism.

- A custom encoder is implemented at the client side ([anycable JS SDK](https://github.com/anycable/anycable-client)) to make encryption/decryption transparent to the user application; that is, your code doesn't really care about encryption.

So, the data flowing through AnyCable is encrypted (and, probably, base64 encoded, since the protocol is text-based), clients can decrypt it back.

**Comment by 0xMostafa** [comment]
Thank you for the detailed response :1st_place_medal:
