### ISSUE TITLE
Looking to implement ticket-based authentication using client IP address

### ISSUE THREAD

**Issue by drdrsh** [anycable/anycable-go#67]
I am trying to implement an authentication method using tickets  (described [here](https://devcenter.heroku.com/articles/websocket-security#authentication-authorization)), but this is impossible to achieve without anycable-go proxying the websocket client ip address to the gRPC server. Is there a way to achieve this?

**Comment by palkan** [comment]
Yes, you can proxy client's IP address to RPC server.

For that, you need to explicitly tell `anycable-go` which headers you want to proxy to RPC server via `--headers` option (or `ANYCABLE_HEADERS` env var). For example:

```
$ anycable-go --headers=x-forwarded-for
```

Then in Connection class:

```ruby
# Rack::Request could infer the IP address from X-FORWARED-FOR
request.ip
# or explicitly
request.headers["HTTP_X_FORWARDED_FOR"]
```

**Comment by sponomarev** [comment]
That works only in case `anycable-go` is behind a reverse proxy.  @drdrsh referred to Heroku docs and in his case, it will work. In more general approach, `anycable-go` doesn't pass this information to RPC server.

I  suggest not to use the header directly because it can turn out that it's a list, not a single address. Besides, different headers can be used. `request.ip` [encapsulates all the complexity inside](https://api.rubyonrails.org/classes/ActionDispatch/RemoteIp.html).
