### ISSUE TITLE
How to install this for mac?

### ISSUE THREAD

**Issue by EsdrasEtrenne** [anycable/anycable-go#8]
I am looking at these files for anycable and my mac will not let me install them because they are not actual files like .dmg, I do not know how to use go but I saw that as the other option for installing anycable-go. How do we install this?

**Comment by palkan** [comment]
Just download the binary (see [Downloads](https://github.com/anycable/anycable-go/blob/master/DOWNLOADS.md)) and update its permissions (`chmod +x path/to/anycable-go`).

In order to run it from anywhere you have to put it somewhere in your PATH, e.g into `/usr/local/bin`.

Or, if you have Go environment installed, you can do: `go get -u -f github.com/anycable/anycable-go`.

I think, it makes sense to add a Homebrew formula. I'll add a corresponding issue.

**Comment by EsdrasEtrenne** [comment]
Ok, thank you. When you say put it somewhere in your PATH you mean the path for the api right? So move the downloaded file into the rails api folder?

**Comment by palkan** [comment]
>  When you say put it somewhere in your PATH you mean the path for the api right?

No, I meant terminal PATH environment variable. It tells your terminal where to look for scripts (thus you don't have to use full paths).

**Comment by EsdrasEtrenne** [comment]
Ok I just  ran:

`sudo ln -s /Downloads/anycable-go-0.4.1-macos-386 /usr/local/bin`

and now it is in the `user/local/bin` folder. I haven't installed something that way before. I also ran the chmod to change the permissions before I moved it.
