### ISSUE TITLE
Exchanging the ActionCable-JSON "frontend" with other Protocol?

### ISSUE THREAD

**Issue by gr8bit** [anycable/anycable-go#91]
I'm currently working on using a custom (ProtoBuf) wrapper for the communication between client and AnyCable server. So I want to get rid of the JSON load ActionCable uses and replace it with specific ProtoBuf definitions for my API (ActionChannel) calls.
The main reasons for this are:
1. Massive savings in Bandwidth
2. Implicitly documented API calls (through .proto files)
3. No datatype-problems (like using int64 in JSON which may or may not be supported)

I figured it might be easiest to leave AnyCable's gRPC-communication with Rails as it is (because it's quite optimal) and add a conversion-layer to AnyCable to convert Rails' ActionCable-responses (over gRPC) into specific ProtoBuf-loads. Unfortunately I've to get a grip on Go first.

My questions (or rather my pleas) to you as AnyCable gurus is: where would you recommend implementing such behavior in the AnyCable code? And what do you think about my approach on ProtoBuf conversion?

Thank you very much in advance! <3

**Comment by palkan** [comment]
> And what do you think about my approach on ProtoBuf conversion?

That's a brilliant idea. We have a similar ticket in our backlog: https://github.com/orgs/anycable/projects/1#card-11340002

Though we were thinking about MsgPack, since it's schema-less, so we don't need to know anything application-specific. Have you considered it?

Does your ProtoBuf schema contain some business-logic specific fields? Or it only represents the Action Cable protocol?

**Comment by gr8bit** [comment]
Wow, thank you for the fast reply! I see we're totally on the same page. :D MsgPack would be a nice general replacement for JSON indeed, regardless of my own case. But I also think that's as far as you can go with pure ActionCable because of ActionCable's "mostly schema-less" data payload ("mostly" because it requires one key to be set in "data" at one occasion). So you need to be open to everything that JSON has to offer, without knowing a schema...

I was planning on having ProtoBuf schemas with specific fields for my business logic though. The clients wouldn't even be (primarily) Webapps with JavaScript in my case but Unity3D clients.

I planned to implement a converting wrapper like this:
- implement a mapping "JSON-payload -> ProtoBuf" (code) for all messages (including the ActionCable-defined ones) for both directions to/from client. I could do this as I know excactly what my client and server will be sending
- (eventually) map all the channels (currently json-encoded strings) to enums using a list of known channels with (optional) zero or more id fields to further minimize packet payload

To be able implement this conversion, I would need one thing however:
A *central point* (or two ;)) in AnyCable-Go where this mapping could happen
1. before the messages (even broadcasts) are being sent to the clients and
2. are received before sending them to the Rails app.

**Comment by gr8bit** [comment]
@palkan, do you have an hints, suggestions or opinions on what I wrote? I'm very interested :)

**Comment by palkan** [comment]
Yeah, sorry, hadn't had time to prepare the reply.

1. For broadcasting, you can hijack this method: https://github.com/anycable/anycable-go/blob/54f63287c577f813f9eb4060a2ff504244e2c3ed/node/hub.go#L253-L259

2. Here is where incoming message is decoded: https://github.com/anycable/anycable-go/blob/54f63287c577f813f9eb4060a2ff504244e2c3ed/node/node.go#L110-L113

So, add proto decode/encode in both places is the first steps.
Then, you need to figure out what would fail due the different frame format (binary instead of text) 🙂 Right now I can't point to specific places in code)

**Comment by gr8bit** [comment]
Thanks a lot! I'll report back :)

**Comment by gr8bit** [comment]
Small update: we're still on it. MessagePack implementation is theoretically done but Protocol Buffers serialization generally needs more input to choose the correct Message to use. That's why we needed to introduce a few api changes... I will attach a PR soon. :)

**Comment by gr8bit** [comment]
Small update: initially we attempted to externalize all the message encoding into a Go plugin (like `message_encoder.so`) but after severe problems with build incompatibilities we've given up on that. I'm currently working on the api changes necessary to be able to build anycable-go with another encoder. Once that runs, I'll do a PR with the API changes for the original JSON encoder.

**Comment by palkan** [comment]
Closing since it has been implemented as a part of Pro version: https://docs.anycable.io/anycable-go/binary_formats
